import { DEFAULT_INTERIOR_FILL, DEFAULT_STROKE } from '../shared/colors';
import type { CatalogDefinition } from '../domain/types';

const baseStyle = {
  fill: DEFAULT_INTERIOR_FILL,
  stroke: DEFAULT_STROKE,
  strokeWidth: 2,
  iconColor: '#203329',
  labelColor: '#203329',
  lineColor: '#f97316',
  lineWidth: 8,
};

export const INTERIOR_DEFINITIONS: CatalogDefinition[] = [
  {
    id: 'interior-table',
    name: 'Table',
    category: 'furniture',
    scope: 'interior',
    shape: 'rectangle',
    defaultSize: { width: 72, height: 30 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 45,
    defaultStyle: baseStyle,
  },
  {
    id: 'interior-chair',
    name: 'Chair',
    category: 'furniture',
    scope: 'interior',
    shape: 'ellipse',
    defaultSize: { width: 24, height: 24 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 12,
    defaultStyle: baseStyle,
  },
  {
    id: 'interior-printer',
    name: 'Printer',
    category: 'office',
    scope: 'interior',
    shape: 'icon',
    defaultSize: { width: 30, height: 24 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 24,
    defaultStyle: baseStyle,
    iconKey: 'printer',
  },
  {
    id: 'interior-tv',
    name: 'TV',
    category: 'electronics',
    scope: 'interior',
    shape: 'icon',
    defaultSize: { width: 48, height: 28 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 18,
    defaultStyle: baseStyle,
    iconKey: 'tv',
  },
  {
    id: 'interior-computer',
    name: 'Computer',
    category: 'electronics',
    scope: 'interior',
    shape: 'icon',
    defaultSize: { width: 28, height: 22 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 15,
    defaultStyle: baseStyle,
    iconKey: 'computer',
  },
  {
    id: 'interior-laptop',
    name: 'Laptop',
    category: 'electronics',
    scope: 'interior',
    shape: 'icon',
    defaultSize: { width: 20, height: 14 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 6,
    defaultStyle: baseStyle,
    iconKey: 'laptop',
  },
  {
    id: 'interior-rack',
    name: 'Rack',
    category: 'network',
    scope: 'interior',
    shape: 'icon',
    defaultSize: { width: 28, height: 36 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 60,
    defaultStyle: baseStyle,
    iconKey: 'rack',
  },
];
