import { DEFAULT_INTERIOR_FILL, DEFAULT_STROKE } from '../shared/colors';
import type { CatalogDefinition } from '../domain/types';

const baseStyle = {
  fill: DEFAULT_INTERIOR_FILL,
  stroke: DEFAULT_STROKE,
  strokeWidth: 2,
  iconColor: '#203329',
  labelColor: '#203329',
  lineColor: '#f97316',
  lineWidth: 8,
};

export const INTERIOR_DEFINITIONS: CatalogDefinition[] = [
  {
    id: 'interior-table',
    name: 'Table',
    category: 'furniture',
    scope: 'interior',
    shape: 'rectangle',
    defaultSize: { width: 72, height: 30 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 45,
    defaultStyle: baseStyle,
  },
  {
    id: 'interior-chair',
    name: 'Chair',
    category: 'furniture',
    scope: 'interior',
    shape: 'ellipse',
    defaultSize: { width: 24, height: 24 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 12,
    defaultStyle: baseStyle,
  },
  {
    id: 'interior-printer',
    name: 'Printer',
    category: 'office',
    scope: 'interior',
    shape: 'icon',
    defaultSize: { width: 30, height: 24 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 24,
    defaultStyle: baseStyle,
    iconKey: 'printer',
  },
  {
    id: 'interior-tv',
    name: 'TV',
    category: 'electronics',
    scope: 'interior',
    shape: 'icon',
    defaultSize: { width: 48, height: 16 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 18,
    defaultStyle: baseStyle,
    iconKey: 'tv',
  },
  {
    id: 'interior-laptop',
    name: 'Laptop',
    category: 'electronics',
    scope: 'interior',
    shape: 'icon',
    defaultSize: { width: 20, height: 14 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 6,
    defaultStyle: baseStyle,
    iconKey: 'laptop',
  },
  {
    id: 'interior-rack',
    name: 'Server',
    category: 'network',
    scope: 'interior',
    shape: 'icon',
    defaultSize: { width: 28, height: 36 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 60,
    defaultStyle: baseStyle,
    iconKey: 'server',
  },
  {
    id: 'interior-spider-box-udb',
    name: 'Spider-Box UDB',
    category: 'power',
    scope: 'interior',
    shape: 'icon',
    defaultSize: { width: 19.5, height: 18.5 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 40,
    defaultStyle: baseStyle,
    iconKey: 'spider-box',
  },
  {
    id: 'interior-refrigerator',
    name: 'Refrigerator',
    category: 'appliance',
    scope: 'interior',
    shape: 'icon',
    defaultSize: { width: 28, height: 28 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 150,
    defaultStyle: baseStyle,
    iconKey: 'refrigerator',
  },
  {
    id: 'interior-pelican-1650',
    name: 'Pelican Case 1650',
    category: 'storage',
    scope: 'interior',
    shape: 'icon',
    defaultSize: { width: 32, height: 20.5 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 30,
    defaultStyle: baseStyle,
    iconKey: 'pelican-case',
  },
  {
    id: 'interior-shredder',
    name: 'Shredder',
    category: 'office',
    scope: 'interior',
    shape: 'icon',
    defaultSize: { width: 16, height: 11 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 45,
    defaultStyle: baseStyle,
    iconKey: 'shredder',
  },
  {
    id: 'interior-white-board',
    name: 'White Board',
    category: 'office',
    scope: 'interior',
    shape: 'icon',
    defaultSize: { width: 28, height: 24 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 15,
    defaultStyle: baseStyle,
    iconKey: 'whiteboard',
  },
  {
    id: 'interior-comms-gear',
    name: 'Comms Gear',
    category: 'network',
    scope: 'interior',
    shape: 'icon',
    defaultSize: { width: 32, height: 20.5 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 30,
    defaultStyle: baseStyle,
    iconKey: 'comms-gear',
  },
  {
    id: 'interior-voip-phone',
    name: 'VOIP Phone',
    category: 'communications',
    scope: 'interior',
    shape: 'icon',
    defaultSize: { width: 12, height: 12 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 3,
    defaultStyle: baseStyle,
    iconKey: 'phone',
  },
  {
    id: 'interior-vtc-unit',
    name: 'VTC Unit',
    category: 'communications',
    scope: 'interior',
    shape: 'icon',
    defaultSize: { width: 22, height: 16 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 8,
    defaultStyle: baseStyle,
    iconKey: 'vtc-unit',
  },
  {
    id: 'interior-coffee-pot',
    name: 'Coffee Pot',
    category: 'appliance',
    scope: 'interior',
    shape: 'icon',
    defaultSize: { width: 12, height: 12 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 3,
    defaultStyle: baseStyle,
    iconKey: 'coffee-pot',
  },
];

export const LEGACY_INTERIOR_DEFINITIONS: CatalogDefinition[] = [
  {
    id: 'interior-computer',
    name: 'Computer',
    category: 'electronics',
    scope: 'interior',
    shape: 'icon',
    defaultSize: { width: 28, height: 22 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 15,
    defaultStyle: baseStyle,
    iconKey: 'computer',
  },
];
