import { DEFAULT_SITE_FILL, DEFAULT_STROKE } from '../shared/colors';
import type { CatalogDefinition } from '../domain/types';

const baseStyle = {
  fill: DEFAULT_SITE_FILL,
  stroke: DEFAULT_STROKE,
  strokeWidth: 2,
  iconColor: '#f5f0e6',
  labelColor: '#f5f0e6',
  lineColor: '#f97316',
  lineWidth: 8,
};

const tentStyle = {
  ...baseStyle,
  fill: '#3d6b3f',
};

export const SITE_DEFINITIONS: CatalogDefinition[] = [
  {
    id: 'tent-103',
    name: '103 Tent',
    category: 'tent',
    scope: 'site',
    shape: 'tent-rect',
    defaultSize: { width: 180, height: 116 },
    rotatable: true,
    resizable: false,
    supportsInterior: true,
    defaultWeightLbs: 272,
    defaultStyle: tentStyle,
    iconKey: 'tent-ridge',
    labelPrefix: '103',
  },
  {
    id: 'tent-105',
    name: '105 Tent',
    category: 'tent',
    scope: 'site',
    shape: 'tent-rect',
    defaultSize: { width: 300, height: 114 },
    rotatable: true,
    resizable: false,
    supportsInterior: true,
    defaultWeightLbs: 358,
    defaultStyle: tentStyle,
    iconKey: 'tent-ridge',
    labelPrefix: '105',
  },
  {
    id: 'tent-307',
    name: '307 Tent',
    category: 'tent',
    scope: 'site',
    shape: 'tent-rect',
    defaultSize: { width: 420, height: 246 },
    rotatable: true,
    resizable: false,
    supportsInterior: true,
    defaultWeightLbs: 741,
    defaultStyle: tentStyle,
    iconKey: 'tent-ridge',
    labelPrefix: '307',
  },
  {
    id: 'tent-305',
    name: '305 Tent',
    category: 'tent',
    scope: 'site',
    shape: 'tent-rect',
    defaultSize: { width: 240, height: 192 },
    rotatable: true,
    resizable: false,
    supportsInterior: true,
    defaultWeightLbs: 390,
    defaultStyle: tentStyle,
    iconKey: 'tent-ridge',
    labelPrefix: '305',
  },
  {
    id: 'tent-dome',
    name: '6D Dome Tent',
    category: 'tent',
    scope: 'site',
    shape: 'tent-hex',
    defaultSize: { width: 373, height: 324 },
    rotatable: true,
    resizable: false,
    supportsInterior: true,
    defaultWeightLbs: 684,
    defaultStyle: tentStyle,
    iconKey: 'tent-hex',
    labelPrefix: '6D',
  },
  {
    id: 'site-generator',
    name: '60 kw Generator',
    category: 'power',
    scope: 'site',
    shape: 'icon',
    defaultSize: { width: 108, height: 40 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 3400,
    defaultStyle: {
      ...baseStyle,
      fill: '#5b4636',
    },
    iconKey: 'generator',
  },
  {
    id: 'site-ecu',
    name: 'ECU',
    category: 'power',
    scope: 'site',
    shape: 'icon',
    defaultSize: { width: 57, height: 34.5 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 730,
    defaultStyle: {
      ...baseStyle,
      fill: '#6b7280',
    },
    iconKey: 'ecu',
  },
  {
    id: 'site-get',
    name: 'Generator ECU Trailer (GET)',
    category: 'power',
    scope: 'site',
    shape: 'icon',
    defaultSize: { width: 162, height: 86 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 3800,
    defaultStyle: {
      ...baseStyle,
      fill: '#8a6742',
    },
    iconKey: 'trailer',
  },
  {
    id: 'site-pdu',
    name: 'Power Distribution Unit (PDU)',
    category: 'power',
    scope: 'site',
    shape: 'icon',
    defaultSize: { width: 36, height: 25 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 50,
    defaultStyle: {
      ...baseStyle,
      fill: '#4b5563',
    },
    iconKey: 'pdu',
  },
  {
    id: 'site-fuel-tank',
    name: 'Fuel Tank (IBC)',
    category: 'fuel',
    scope: 'site',
    shape: 'icon',
    defaultSize: { width: 48, height: 40 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 150,
    defaultStyle: {
      ...baseStyle,
      fill: '#64748b',
    },
    iconKey: 'fuel-tank',
  },
  {
    id: 'site-container',
    name: 'Storage Container',
    category: 'storage',
    scope: 'site',
    shape: 'icon',
    defaultSize: { width: 240, height: 96 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 5000,
    defaultStyle: {
      ...baseStyle,
      fill: '#6c757d',
    },
    iconKey: 'container',
  },
  {
    id: 'site-isu-90',
    name: 'ISU-90',
    category: 'storage',
    scope: 'site',
    shape: 'rectangle',
    defaultSize: { width: 108, height: 88 },
    rotatable: true,
    resizable: false,
    supportsInterior: true,
    defaultWeightLbs: 3310,
    defaultStyle: {
      ...baseStyle,
      fill: '#7c6f5c',
    },
    iconKey: 'container',
    labelPrefix: 'ISU-90',
  },
  {
    id: 'site-antenna',
    name: 'Antenna',
    category: 'antenna',
    scope: 'site',
    shape: 'icon',
    defaultSize: { width: 60, height: 60 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultStyle: {
      ...baseStyle,
      fill: '#355070',
    },
    iconKey: 'antenna',
  },
  {
    id: 'site-tree',
    name: 'Tree / Obstacle',
    category: 'obstacle',
    scope: 'site',
    shape: 'icon',
    defaultSize: { width: 72, height: 72 },
    rotatable: false,
    resizable: true,
    supportsInterior: false,
    includeInPackingList: false,
    defaultStyle: {
      ...baseStyle,
      fill: '#2f6f4f',
    },
    iconKey: 'tree',
  },
  {
    id: 'site-berg-shelter',
    name: 'BERG Shelter',
    category: 'structure',
    scope: 'site',
    shape: 'rectangle',
    defaultSize: { width: 233, height: 213.5 },
    rotatable: true,
    resizable: false,
    supportsInterior: true,
    defaultWeightLbs: 3425,
    defaultStyle: {
      ...baseStyle,
      fill: '#84705d',
    },
    iconKey: 'structure-top',
    labelPrefix: 'BERG',
  },
  {
    id: 'site-structure',
    name: 'Building',
    category: 'structure',
    scope: 'site',
    shape: 'rectangle',
    defaultSize: { width: 300, height: 180 },
    rotatable: true,
    resizable: true,
    supportsInterior: true,
    defaultWeightLbs: 0,
    defaultStyle: {
      ...baseStyle,
      fill: '#84705d',
    },
    iconKey: 'structure-top',
    labelPrefix: 'Building',
  },
];
