import { DEFAULT_SITE_FILL, DEFAULT_STROKE } from '../shared/colors';
import type { CatalogDefinition } from '../domain/types';

const baseStyle = {
  fill: DEFAULT_SITE_FILL,
  stroke: DEFAULT_STROKE,
  strokeWidth: 2,
  iconColor: '#f5f0e6',
  labelColor: '#f5f0e6',
  lineColor: '#f97316',
  lineWidth: 8,
};

export const SITE_DEFINITIONS: CatalogDefinition[] = [
  {
    id: 'tent-105',
    name: '105 Tent',
    category: 'tent',
    scope: 'site',
    shape: 'tent-rect',
    defaultSize: { width: 240, height: 120 },
    rotatable: true,
    resizable: false,
    supportsInterior: true,
    defaultWeightLbs: 300,
    defaultStyle: baseStyle,
    iconKey: 'tent-ridge',
    labelPrefix: '105',
    description: 'Placeholder dimensions. Update with measured specs before release.',
  },
  {
    id: 'tent-307',
    name: '307 Tent',
    category: 'tent',
    scope: 'site',
    shape: 'tent-rect',
    defaultSize: { width: 288, height: 192 },
    rotatable: true,
    resizable: false,
    supportsInterior: true,
    defaultWeightLbs: 420,
    defaultStyle: baseStyle,
    iconKey: 'tent-ridge',
    labelPrefix: '307',
    description: 'Placeholder dimensions. Update with measured specs before release.',
  },
  {
    id: 'tent-305',
    name: '305 Tent',
    category: 'tent',
    scope: 'site',
    shape: 'tent-rect',
    defaultSize: { width: 240, height: 192 },
    rotatable: true,
    resizable: false,
    supportsInterior: true,
    defaultWeightLbs: 390,
    defaultStyle: baseStyle,
    iconKey: 'tent-ridge',
    labelPrefix: '305',
    description: 'Placeholder dimensions. Update with measured specs before release.',
  },
  {
    id: 'tent-dome',
    name: 'Dome Tent',
    category: 'tent',
    scope: 'site',
    shape: 'tent-dome',
    defaultSize: { width: 120, height: 120 },
    rotatable: true,
    resizable: false,
    supportsInterior: true,
    defaultWeightLbs: 80,
    defaultStyle: baseStyle,
    iconKey: 'tent-dome',
    labelPrefix: 'Dome',
    description: 'Placeholder dimensions. Update with measured specs before release.',
  },
  {
    id: 'site-generator',
    name: 'Generator',
    category: 'power',
    scope: 'site',
    shape: 'icon',
    defaultSize: { width: 72, height: 48 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 950,
    defaultStyle: {
      ...baseStyle,
      fill: '#5b4636',
    },
    iconKey: 'generator',
  },
  {
    id: 'site-container',
    name: 'Storage Container',
    category: 'storage',
    scope: 'site',
    shape: 'icon',
    defaultSize: { width: 240, height: 96 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultWeightLbs: 5000,
    defaultStyle: {
      ...baseStyle,
      fill: '#6c757d',
    },
    iconKey: 'container',
  },
  {
    id: 'site-antenna',
    name: 'Antenna',
    category: 'antenna',
    scope: 'site',
    shape: 'icon',
    defaultSize: { width: 60, height: 60 },
    rotatable: true,
    resizable: false,
    supportsInterior: false,
    defaultStyle: {
      ...baseStyle,
      fill: '#355070',
    },
    iconKey: 'antenna',
  },
  {
    id: 'site-tree',
    name: 'Tree / Obstacle',
    category: 'obstacle',
    scope: 'site',
    shape: 'icon',
    defaultSize: { width: 72, height: 72 },
    rotatable: false,
    resizable: true,
    supportsInterior: false,
    defaultStyle: {
      ...baseStyle,
      fill: '#2f6f4f',
    },
    iconKey: 'tree',
  },
  {
    id: 'site-structure',
    name: 'Hardened Structure',
    category: 'structure',
    scope: 'site',
    shape: 'rectangle',
    defaultSize: { width: 300, height: 180 },
    rotatable: true,
    resizable: true,
    supportsInterior: true,
    defaultWeightLbs: 0,
    defaultStyle: {
      ...baseStyle,
      fill: '#84705d',
    },
    iconKey: 'structure-top',
    labelPrefix: 'Structure',
  },
];
